java/RotateImage.java, java/hellowordl.java
[Added java soltuion for rotate image problem in leetcode (lc number 48) .
=> Added new leetcode problem solution

c++/Binary Trees/boundary_traversal.cpp, c++/Binary Trees/chack_balance.cpp, c++/Binary Trees/level_order_traversal.cpp, c++/Binary Trees/max_depth_of_tree.cpp, c++/Binary Trees/mirror_check_tree.cpp, c++/Binary Trees/symmetric_check_tree.cpp, c++/Binary Trees/top_view_tree.cpp, c++/Binary Trees/vertical_traversal.cpp, c++/Graphs/course_scheduling.cpp, c++/Graphs/cycle_detection_graoh_directed_BFS.cpp, c++/Graphs/flood_fill_leetcode.cpp, c++/Graphs/number_of_islands.cpp, c++/Graphs/orange_rotting.cpp, c++/Graphs/word_ladder.cpp, c++/Graphs/word_ladder_2.cpp
Added C++ solutions for fundamental Graph problems from LeetCode, covering key algorithms and interview-relevant patterns:
- course_scheduling.cpp
- cycle_detection_graoh_directed.cpp
- flood_fill_leetcode.cpp
- number_of_islands.cpp
- orange_rotting.cpp
- word_ladder.cpp
- word_ladder_2.cpp
These problems represent some of the most frequently asked graph questions in technical interviews and coding contests. They cover core concepts such as:
- Topological sorting and cycle detection
- BFS/DFS traversal patterns
- Connected components in grids
- Shortest path in unweighted graphs
- Multi-source BFS applications
Together, they form a strong base for mastering graph theory and problem solving.
=> Add Graph algorithm solutions (LeetCode Top Questions)

python/longest word in sentence.py
Python solution for finding longest word in a given sentance.
=> docs: Added longest word in sentance soln.

python/longest word in sentence.py, python/palindrome check.py
Added Palindrome check solution in python.
=> Added Palindrome check

python/3Sum.py, python/Container_With_Most_Water.py, python/FindMinimumInRotatedSortedArray.py, python/Group_Anagrams.py, python/Missing_Number.py, python/SearchInRotatedSortedArray.py, python/Spiral_Matrix.py, python/Two_Sum.py, python/maximum_product_Subarray.py
This PR adds solutions for classic DSA Array problems in Python:
1. Two Sum – Find indices of two numbers that add up to a target.
2. Container With Most Water – Calculate the maximum area of water that can be contained.
3. Maximum Product Subarray – Find the contiguous subarray with the maximum product.
4. 3Sum – Find all unique triplets in the array which gives the sum of zero.
=> Added Python DSA Code

c++/StringtoInteger(atoi).cpp, c++/findMedianSortedArrays.cpp
Added 2 C++ DSA code
1.Find Median Sorted Array
2.String to Integer
=> Added C++ DSA code

python/Search in rotated array.py
added search in rotated array code in python language
=> added search in rotated array code in python language

C/towerofhanoi.c, java/linkedlistsum.java, python/towerofhanoi.py
1.Tower of hanoi in c
2.Tower of hanoi in python 
3.Sum of linkedlist in java
=> added code in c java python

python/Singly Linked List(Music playlist Simulation).py, python/stack(finding greater number).py
**Added Python DSA(stack and singly linked list--application based)**
1.Added Stack based application(of finding the next greater number in the array and printing "-1" if no greater number found)
2.Added Singly linked application(Music playlist operations)
=> Added an application of stack and singly linked list(python)

.vscode/c_cpp_properties.json, javascript/1darray.js, javascript/sum.js
Added JavaScript DSA codes
1)  JavaScript code to add two numbers represented as linked lists
2) A JavaScript program that performs common operations on a 1D array, such as
-        Traversal
-        Insertion
-        Deletion
-        Searching
-        Updating
=> Added JavaScript DSA codes

java/Median of two sorted array.java
Added Java DSA Code
Median of two sorted array.java
=> Added Java DSA code

python/max_subarray.py, python/sliding_window.py
=> Update: Added sliding window

c++/count_factors.cpp, c++/first_last_position.cpp, c++/squares_of_sorted_array.cpp
Added 3 classic DSA solutions in **C++**:
1. **Squares of a Sorted Array** – Generate a new array of squares from a sorted array, also sorted. (Two Pointers pattern)  
2. **First and Last Position of Element in Sorted Array** – Find the first and last positions of a target element. (Binary Search pattern)  
3. **Count Factors of a Number** – Count the total number of factors of a given number. (Number Theory pattern)
=> Added c++ DSA solutions

c++/reverseString.cpp, c++/validPalindrome.cpp
Added the solution of reversing a string in c++
=> Added reverse a string code in c++

python/lengthOflongestsubstring.py
Problem : to find length of longest substring
=> Python dsa code Added!

python/check prime.py, python/factorial.py
=> Check for prime

javascript/hellowordl.js, javascript/zigzagpattern.js
Solved a LeetCode DSA problem using JavaScript.
Question: Write string "PAYPALISHIRING" in a zigzag pattern
Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
=> LeetCode ZigZag Problem Solved with JS

javascript/calculator.js
you can use the file to import the js function for doing arithmetic operations.
=> added a calculator function

python/print_circular_array.py
- Added a function to print all circular rotations of a given array.
- Included input validation to check array size constraints (2 <= size <= 10).
- Handles invalid inputs and mismatched array lengths gracefully.
- Tested with sample inputs as given in the issue.
1. Run the program.
2. Input array size (integer between 2 and 10).
3. Input array elements separated by spaces.
4. Observe all circular rotations printed in order.
- Assumes the user enters the correct number of elements as per the array size.
- Uses Python list slicing for rotation efficiency.
=> Added solution for print_circular_array in python

c++/aggressive_cows.cpp, c++/book_allocation.cpp
This pull request adds two binary search-based algorithm solutions written in C++ to the repository:
**Aggressive Cows:** Solves the problem of finding the maximum minimum distance to place cows in stalls.
**Book Allocation:** Determines the minimum maximum pages that can be allocated to each student.
**Context**
These implementations are contributed as part of Hacktoberfest 2025 to enhance the repository's collection of algorithmic solutions. Both problems utilize binary search to optimize the search for the maximum minimum value, making them valuable learning resources for contributors interested in competitive programming.
**Changes Made**
**Added aggressive_cow.cpp with:**
A function aggressiveCows that uses binary search to find the maximum minimum distance.
Helper function …
=> add C++  aggressive-cow and book-allocation problem code

java/LargestSubarraySum.java
Added following code->
find largest subarray sum  in LargestSubarraySum.java
This problems is solved using Kadane algorithm
=> Added solution for largestSubarraySum in java

c++/climbing_stairs.cpp, c++/house_robber.cpp
Added following codes->
1) climbing stairs - (leetcode 70) --climbing_stairs.cpp
2) house robber- (leetcode 198)  --house_robber.cpp
these both problems are solved using Dynamic Programming using optimal Recursion + memoization approach
=> Added cpp codes

python/binary_search.py, python/bubble_sort.py, python/fibonacci.py, python/linear_search.py, python/merge_sort.py, python/palindrome_checker.py, python/queue_implementation.py, python/reverse_linked_list.py, python/selection_sort.py, python/stack_implementation.py
Added python codes
1)binary_search.py
bubble_sort.py
fibonacci.py
linear_search.py
merge_sort.py
palindrome_checker.py
queue_implementation.py
reverse_linked_list.py
selection_sort.py
stack_implementation.py
=> changes are made

c++/merge_sort.cpp
added a merge sort code in c++
=>  added merge sort code in c++

python/Binary_tree_Paths.py
Added one Python DSA code:
1) Binary_tree_Paths.py
=> Implemented DFS approach to collect all root-to-leaf paths in a binary tree.

rust/Task.rs
- Developed a task-based middleware system in Rust utilizing the Rayon crate for data parallelism.
- Implemented a Scheduler struct that manages a collection of tasks and provides methods to add and execute them.
- Employed Arc and Mutex to safely share and mutate the list of tasks across threads.
- Designed the system to support composable scheduling policies, allowing for easy extension to different scheduling strategies.
- Demonstrated the system by executing tasks with varying durations concurrently.
=> Implement task-based middleware with composable scheduling policies in Rust

ruby/JobRegistry.rb
- Created a dynamic distributed job processing framework in Ruby.
- Includes Job base class with automatic registration via metaprogramming.
- Implements EmailJob and ReportJob as example jobs.
- Added JobRegistry singleton to track available jobs.
- Developed ThreadPool for concurrency management.
- Added JobScheduler to dynamically schedule jobs by name.
- Included JobLoader to simulate dynamic plugin discovery and loading.
- Demonstrates advanced Ruby features:
- Metaprogramming
- Threading and concurrency
- Singleton pattern
- Dynamic job scheduling
- Dependency injection
- Serves as a professional‑grade example of Ruby concurrent system design.
=> Implement dynamic distributed job processor framework in Ruby

python/TaskMeta.py
- Added a dynamic async pipeline system using metaclasses and asyncio.
- Created a base Task class and example tasks (TaskA, TaskB, TaskC).
- Used TaskMeta metaclass to auto-register tasks.
- Developed Pipeline class to execute tasks in sequence asynchronously.
- Demonstrates advanced Python features:
- Metaclasses
- Asynchronous programming
- Dynamic pipeline construction
- Reflection and task auto-registration
- Serves as a complex Python concurrency and architecture example.
=> Implement dynamic async task pipeline system in Python

php/TaskQueue.php
Add multi-threaded task queue implementation in PHP
- Implemented a multi-threaded task queue in PHP using the pthreads extension.
- Created a Task class extending Thread to encapsulate concurrent work.
- Developed a TaskQueue class to manage dynamic tasks and concurrency limits.
- Demonstrates advanced PHP features including:
- Multi-threading in PHP
- Dynamic task scheduling
- Resource management and synchronization
- Serves as a complex example of PHP concurrency for CLI applications.
=> Add multi-threaded task queue implementation in PHP

javascript/merge-sort-algo.js
Hi There!
In this PR, I added a merge sort algorithm for JS programmers. Please have a look and provide me feedback if you have.
Thanks.
=> chore: add merge sort algorithm in javascript

C/Queue.c, python/Circularqueue.py, python/Double_endedcircularqueue.py
Added 3 Python DSA codes
1)Circularqueue.py
2)Double_endedcircularqueue.py
=> Added Python dsa Circular and Double_circular Queue codes

java/1518-Water-Bottles/README.md, java/1518-Water-Bottles/water-bottles.java
- I created a folder inside Java as "_1518-Water-Bottles_"
- There I created two files:
> - water-bottles.java: File where the solution is present
> - README.md: File where description about the problem statement is mentioned
=> Solution to todays daily problem in Java is added with a description of the problem statement.

c++/Graphs/number_of_enclaves.cpp
Added in CPP Graphs
1) Number of Enclaves
=> feat(graph): added number of enclaves in cpp

.vscode/settings.json, c++/Compute_decimal_representation.cpp
You are given a positive integer n.
A positive integer is a base-10 component if it is the product of a single digit from 1 to 9 and a non-negative power of 10. For example, 500, 30, and 7 are base-10 components, while 537, 102, and 11 are not.
Express n as a sum of only base-10 components, using the fewest base-10 components possible.
Return an array containing these base-10 components in descending order.
Example 1:
Input: n = 537
Output: [500,30,7]
Explanation:
We can express 537 as 500 + 30 + 7. It is impossible to express 537 as a sum using fewer than 3 base-10 components.
Example 2:
Input: n = 102
Output: [100,2]
Explanation:
We can express 102 as 100 + 2. 102 is not a base-10 component, which means 2 base-10 components are needed.
=> added solution for 3687.Compute Decimal Representation Leetcode problem in cpp.

typscript/apiResponseHandler.ts
- Created a generic ApiResponse type to handle API responses with type safety.
- Implemented ApiResponseHandler interface to define a consistent method for handling responses.
- Developed specific handlers for User and Product API responses.
- Demonstrated the use of recursive types, mapped types, conditional types, template literal types, and utility types.
- Enhanced code maintainability and type safety by leveraging TypeScript's advanced type system.
=> Implement type-safe API response handler using advanced TypeScript features

python/bellman_ford.py, python/kmp_search.py, python/kruskals_algorithm.py, python/prims_algorithm.py
I added 4 Python DS codes
1. bellman_ford.py
2. kmp_search.py
3. prims_algorithm.py
4. kruskals_algorithm.py
=> Added Python DSA algorithm code

c++/3100-Water-Bottles-II.cpp, c++/Counting-Sort.cpp, c++/Quick-Sortt.cpp
- Added beginner-friendly implementation of Quick Sort (Quick-Sortt.cpp).
- Added beginner-friendly implementation of Counting Sort (Counting-Sort.cpp).
- Both codes include clear comments for easy understanding by beginners.
- These additions enhance the sorting algorithms section of the repository.
=> Added Quick Sort and Counting Sort implementations in C++

c++/3100-Water-Bottles-II.cpp, c++/Counting-Sort.cpp, c++/Quick-Sortt.cpp
I've included the LeetCode problem of the day from October 2nd, along with my C++ solution.
=> Updated Leetcode POTD of 2 OCT in CPP

c++/friendfunction.cpp
=> Added friend function

C/Climbing_Stairs.c, C/FrogJump.c, C/leastCommonSubsequence.c
**### Description**
**Added three Dynamic Programming solutions in C:**
1) Frog Jump
2) Longest Common Subsequence (LCS)
3) Climbing Stairs
Each problem is solved in a separate file.
Code is simple, clean, and well-commented for understanding.
**Checklist**
Added new code files
Follows problem statement requirements
Tested with sample inputs
=> Add Dynamic Programming solutions in C (Frog Jump, LCS, Climbing Stairs)

C/Climbing_Stairs.c, C/FrogJump.c, C/leastCommonSubsequence.c, c++/linkedlist_basics.cpp, c++/linkedlist_detect_cycle.cpp, c++/linkedlist_reverse.cpp
This PR adds three separate C++ code files implementing common Linked List problems.
- `linkedlist_basics.cpp` → Create, insert, and print a linked list  
- `linkedlist_reverse.cpp` → Reverse a linked list (iterative)  
- `linkedlist_detect_cycle.cpp` → Detect a cycle using Floyd’s Cycle Detection Algorithm  
- Contribute standard DSA implementations in C++  
- Beginner-friendly examples with clear comments  
- Useful for learners preparing for coding interviews  
- All files compiled and executed successfully using `g++`.  
- Outputs verified for correctness:
- Basics → `10 -> 20 -> 30 -> NULL`
- Reverse → `30 -> 20 -> 10 -> NULL`
- Cycle detection → `Cycle detected in linked list!`
- No existing files were modified  
- Safe to merge (no conflicts)
---
As this contribution is part of …
=> Added Linked List implementations in C++ (Basics, Reverse, Cycle Detection)

java/mergeSort.java
Add Java DSA codes
1. Java program for Bubble Sort
2. Java implementation of Merge Sort
=> Add Java DSA codes

python/DynamicProgramming/CoinChange.py, python/DynamicProgramming/Knapsack01.py, python/DynamicProgramming/LongestCommonSubsequence.py
This PR adds three classic **Dynamic Programming (DP) problems** in Python under the `Python/DynamicProgramming/` folder.  
Each problem is implemented with an **optimal approach**, includes **example usage**, **explanation**,and contains **time & space complexity analysis**.
1. Coin Change – Minimum coins to form a target amount (1D DP)
2. 0/1 Knapsack – Maximize value for a given weight limit (2D DP)
3. Longest Common Subsequence – Find LCS of two strings (2D DP)
- Added `Python/DynamicProgramming/` folder for all DP problems.
- -Added file for each problem.
- Each file is **well-commented**, **clean**, and **runnable**.
- Ensures consistency across all DP implementations.
- Provides **example input/output** for quick verification.
---
- Help learners explore **optimal DP solutions**.
- …
=> Added  Dynamic Programming Problems in Python

python/palindrome_check.py
I executed the code to check Palindrome in Python
=> added Palindrome checking code

python/dijkstra's_algorithm.py, python/palindrome_check.py
i executed dijkstra's algorithm using priority queue in python
=> Dijkstra algorithm

go/quick_sort.go, python/dijkstra's_algorithm.py, python/palindrome_check.py
i added the quick sort algorithm in Go
=> Quick sort

go/quick_sort.go, python/dijkstra's_algorithm.py, python/palindrome_check.py, python/topological_sort.py
i executed topological sort using Python
=> Topological sort (Kahn's algorithm) using Python

java/characterReplacement.java, java/moveZeros.java
This PR adds two efficient algorithm implementations to the Java DSA collection:
Changes Added:
**1. Move Zeros Algorithm (moveZeros.java)**
- Moves all zeros in an array to the end while preserving non-zero element order
- Uses two-pointer technique for O(n) time, O(1) space complexity
- In-place array modification with swap operations
**2. Longest Repeating Character Replacement (characterReplacement.java)**
- Finds longest substring with same characters after at most k replacements
- Implements sliding window approach with character frequency tracking
- O(n) time complexity using left/right pointers
**Test Cases**
- Move Zeros: [0,1,0,3,12] → [1,3,12,0,0]
- Character Replacement: "AABABBA" with k=1 → length 4
Both implementations include comprehensive test cases and demonstrate …
=> Add Two Array/String Algorithm Implementations in Java

C/selectionsort.c
=> added code in c

C/1d_array_sum.c, C/binarysearch.c, C/gcd.c, C/stringpalindrome.c
1) binary search
2) sum of 1d array
3) gcd of two numbers
4) whether string is palindrome
=> added codes in c

javascript/Fenwick.js
=> Fenwick tree in javascript

ruby/fenwick_Tree.rb
=> Fenwick Tree in ruby

ruby/warshsall_algo.rb
=> Warshalls Algorithm in ruby

typscript/binary_search.ts
=> binary-search

java/NQueens.java, java/NQueens2.java, java/WaterBottles.java, java/Waterbottles2.java
Added 2 DSA Java Code
1)Water Bottles (leetcode 1518)
1)Water Bottles 2(leetcode 3100)
=> Added Java DSA Code (water bottles)

c++/TwoSum.cpp, c++/water_bottle.cpp, java/BinarySearchTree.java, java/BinaryTree.java, java/Driver.java, python/4Sum.py
This PR implements the 4Sum algorithm to find all unique quadruplets [a, b, c, d] in an integer array such that a + b + c + d == target. The solution uses sorting and a two-pointer approach to achieve a time complexity of O(n³).
**📋 Details**
Input: nums (List[int]), target (int)
Output: List of unique quadruplets that sum to the target
Time Complexity: O(n³) using sorting and two-pointer optimization
Space Complexity: O(1) (ignoring output space)
**🎯 Key Features**
Uses three nested loops (two indices + two-pointer) for efficient traversal
Early termination checks to reduce unnecessary iterations
Handles duplicates to ensure unique results
Covers edge cases like:
Empty input
Duplicates in the array
Extreme target values or integer limits
**📌 Example**
Input: nums = [1, 0, -1, 0, -2, 2], …
=> 4Sum Solution in Python

javascript/rhombus_pattern.js, javascript/single_number.js
This PR adds two new solutions:
1. **Single Number Problem**
- Implemented solution using XOR approach to find the unique number in an array.
- Includes inline comments and an example for clarity.
- 
2. **Rhombus Pattern**
- Implemented program to print a solid rhombus pattern.
- Added JavaScript version with explanatory comments and example output.
- Single Number (`[4,1,2,1,2]`): Output = 4
- Rhombus Pattern (`n = 5`):
<pre>
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 
</pre>
Both solutions include comments and examples for better understanding.
=> Add solutions for Rhombus Pattern and Single Number problem

python/Dijkstra’s_Algo.py, python/graph_bfs.py, python/graph_dfs.py, python/undirected_graph_dfs.py
Added Python DSA Graph problems
1. BFS Traversal
2. DFS Traversal
3. Detect Cycle in Undirected Graph
4. Dijkstra’s Algorithm (Shortest Path)
=> Added solved python dsa graph problems

hello_world.py
Fix syntax error in print statement.
=> Correct print statement in hello_world.py

python/bfs.py, python/detect_cycle_undirected.py, python/dfs.py, python/graph_adjacency_list.py
Summary
This PR introduces Python implementations of fundamental graph algorithms that cover traversal, shortest paths, cycle detection, and ordering of directed graphs.
Files Added
graph_bfs.py — Implements Breadth-First Search (BFS) for graph traversal
graph_dfs.py — Implements Depth-First Search (DFS) for graph traversal
dijkstra_algorithm.py — Implements Dijkstra’s algorithm for shortest path calculation
detect_cycle_graph.py — Detects cycles in a graph (both directed and undirected)
topological_sort.py — Performs topological sorting on Directed Acyclic Graphs (DAGs)
=> Tree Algorithm for Python

python/binary_search_tree.py, python/binary_tree_traversal.py, python/lowest_common_ancestor.py, python/tree_height.py
Summary
This PR adds Python implementations of essential tree algorithms focused on binary trees and binary search trees (BSTs), which are fundamental for understanding hierarchical data structures.
Files Added
binary_tree_traversal.py — Implements various tree traversals (inorder, preorder, postorder)
binary_search_tree.py — Implements basic operations on a Binary Search Tree (insertion, search, deletion)
lowest_common_ancestor.py — Finds the Lowest Common Ancestor (LCA) of two nodes in a binary tree
tree_height.py — Calculates the height of a binary tree
=> Trees Algorithms

python/factorial_recursion.py, python/fibonacci_recursion.py, python/maze_solver.py, python/n_queens_problem.py, python/sudoku_solver.py
Summary
This PR introduces Python implementations of key problems solved using recursion and backtracking, which are crucial concepts in algorithm design and problem-solving.
Files Added
factorial_recursion.py — Calculates factorial of a number using recursion
fibonacci_recursion.py — Generates Fibonacci numbers using recursion
n_queens_problem.py — Solves the N-Queens problem using backtracking
sudoku_solver.py — Solves Sudoku puzzles using backtracking
maze_solver.py — Finds paths in a maze using backtracking
=> Algorithm for recursion and Backtracking

ruby/bubble_sort.rb
Implemented bubble sort in ruby
=> bubble_sort ruby

python/LinearSearch.py
How it works:
Goes through each element of the list one by one.
Compares it with the target value.
Returns the index if found, otherwise returns -1.
=> LinearSearch.py

c++/sum_of_1d_array.cpp
IN C++:
1) Added the code to sum of array elements
=> sum of array in c++

ruby/bubble_sort.rb, ruby/merge_sort.rb
=> Merge sort in ruby

c++/merge_K_sorted_lists.cpp, c++/skyline_problem.cpp
Hello! My name is Bhavishy Agrawal.
This is my second pull request for Hacktoberfest 2025.
I've implemented the code for merging K sorted linked lists in C++.
I've tried to keep my pull request and code genuine and clean for understanding.
Kindly merge my pull request :)
=> Added code for merging K sorted linked lists in C++

python/N-Queens.py
This PR adds a complete implementation of the N-Queens problem using backtracking algorithm in Python.
- ✅ Efficient backtracking solution
- ✅ Uses sets for O(1) conflict checking
- ✅ Handles positive and negative diagonal conflicts
- ✅ Interactive input for board size
- ✅ Displays all possible solutions
- ✅ Clean, well-commented code
- **Time Complexity**: O(N!)
- **Space Complexity**: O(N)
- **Approach**: Backtracking with constraint propagation
- **Optimization**: Uses sets to track column and diagonal conflicts
- `python/N-Queens.py` - Complete N-Queens solver implementation
The solution has been tested with various board sizes and produces correct results for all valid N-Queens configurations.
- ✅ Added DSA-related problem solution
- ✅ Clean, well-commented code
- ✅ Proper file …
=> Add N-Queens Problem Solution in Python

c++/PizzaWith3nSlices.cpp, java/wildcard.java
Added wildcard matching problem using two pointer approach in java
=> added wildcard matching code in java

java/Arrays/Longest_Consecutive_Sequence_in_an_Array.java
This pull request adds a new Java implementation for finding the longest consecutive sequence in an array. The file includes both a brute-force and an optimal solution, along with a sample usage in the `main` method.
Algorithms for finding longest consecutive sequence:
* Added brute-force method `longestSuccessiveElements` using linear search to find consecutive elements in an array.
* Added optimal method `longestSuccessiveElementsOptimal` using a `HashSet` to achieve better performance by checking for sequence starts and counting consecutive elements.
Code organization and documentation:
* Created new file `Longest_Consecutive_Sequence_in_an_Array.java` under the `Arrays` package, including author attribution and GitHub link.
* Provided a sample `main` method demonstrating usage of the …
=> Longest_Consecutive_Sequence_in_an_Array

java/PascalTriangle.java
Added a algorithm of Pascal's triangle implemented in java
=> Added solution for pascal's Triangle in java

c++/splitarray.cpp
added the solution to this leetcode question
Given an integer array nums and an integer k, split nums into k non-empty subarrays such that the largest sum of any subarray is minimized.
Return the minimized largest sum of the split.
A subarray is a contiguous part of the array.
Example :
Input: nums = [7,2,5,10,8], k = 2
Output: 18
Explanation: There are four ways to split nums into two subarrays.
The best way is to split it into [7,2,5] and [10,8], where the largest sum among the two subarrays is only 18.
=> solution to split array sum

c++/findduplicates.cpp
Implemented a C++ program to find duplicate elements in an array.
- Added `find-duplicates.cpp` file inside the C++ folder.
- The program takes input array from user and prints all duplicate elements.
Input: 1 3 4 2 2 3 5
Output: 2 3
=> Added C++ Solution For Find Duplicates Problem

BIn search CPP, c++/binary, c++/bubble, c++/gcd, c++/insertion, c++/linear, c++/selection, gcd.cpp, ins code, sel sort
=> Create BIn search CPP

python/min_parentheses.py, python/uniquePerms.py
Implement minParentheses function to calculate minimum insertions required for balanced parentheses
=> Min parantheses

C/towerofhanoi.c, java/linkedlistsum.java, python/towerofhanoi.py
1)Tower of hanoi in c
2)Tower of hanoi in python
3)sum of linked;ist in java
=> Added code in python c java

C/sortarray.c, python/sumof2darray.py
heres a simple 2d array code using python
=> Added Python 2d array code

c++/longest_consecutive_sequence.cpp
Problem: Longest Consecutive Sequence (LeetCode 128)
What this code does:
- Accepts an unsorted integer array as input.
- Finds the length of the longest consecutive sequence in the array.
- Uses `unordered_set` for O(1) lookup to efficiently check consecutive numbers.
- Starts sequences only at numbers that don’t have a smaller consecutive predecessor.
- Runs in O(n) time complexity.
- Outputs the length of the longest consecutive sequence.
Example:
```
Input: [100, 4, 200, 1, 3, 2]
Output: 4   // sequence [1,2,3,4]
```
=> Add Longest Consecutive Sequence problem in C++ (LeetCode 128)

java/SpiralMatrix.java
This pull request adds the corrected version of SpiralMatrix.java.
1. SpiralMatrix.java
=> Added Spiral Matrix in java

java/TwoPointer.java
This Java program uses the Two Pointer technique to find a pair of numbers in a sorted array that sum up to a given target. It moves one pointer from the start and one from the end, adjusting them until the target sum is found or all pairs are checked.
=> Add Two Pointer Algorithm

java/LinkedListCycleDetection.java
Added Linked List Cycle Detection solution in Java
=> Add Linked List Cycle Detection solution in Java

c++/Square_Root_Decomposition.cpp
Summary
Implemented Square Root Decomposition in C++ to efficiently handle range sum queries.
Details
Added block decomposition logic with preprocessing of array into block sums.
Implemented a method to answer range sum queries in O(√n) time.
Prepared the structure to allow future updates and extensions.
Why?
This improves query performance from O(n) per query to O(√n), making it suitable for large datasets and competitive programming scenarios.
=> Square Root Decomposition

php/even.php, php/fibonacci.php, php/prime.php
add 3 file 
1) php/even.php
2) php/prime.php
3) php/fibonacci.php
=> write code in php (even,prime , fibonacci) vaibhavbabele

c++/Queues/01Arrayimplementationofqueue.cpp, c++/Queues/02vectorImplementationofqueue.cpp, c++/Queues/03DesignaDeque.cpp, c++/Queues/04DequeSTL.cpp, c++/Queues/05DesignCircularQueueLeetcode-622.cpp, c++/Queues/06ReversefirstKelementsofaQueue.cpp, c++/Queues/07NumberofStudentsUnabletoeatLunch_LC-1700.cpp, c++/Queues/08ImplementQueueusingStacks_Leetcode-232.cpp, c++/Queues/09RevealCardsinIncreasingOrderLeetcode-950.cpp, c++/Stack/01stackprint.cpp, c++/Stack/02reversestack.cpp, c++/Stack/03ArrayImplementationof_Stack.cpp, c++/Stack/04LinkeoListImplementation.cpp, c++/Stack/05RemoveConsecutiveDuplicatesinastring.cpp, c++/Stack/06Nextgreaterelement.cpp, c++/Stack/07Previousgreaterelement.cpp, c++/Stack/08Stock_Span_problem.cpp, c++/Stack/09infix_string_calculation.cpp, c++/Stack/10infix_string_calculationwithBracket.cpp, c++/Stack/11InfixtoPrefixConversion.cpp, c++/Stack/12InfixtoPostfixConversion.cpp, c++/Stack/13PostfixEvaluation.cpp, c++/Stack/14PostfixtoInfixConversion.cpp, c++/Stack/15PostfixtoPREFIXConversion.cpp, c++/Stack/16PrefixEvaluation.cpp, c++/Stack/17PrefixtoInfixConversion.cpp, c++/Stack/18PrefixtoPostfixConversion.cpp
i) Queue Implementations
1. Vector-based queue with push, pop, front, back, size, empty, and display
2. Deque using a doubly linked list (push/pop from both ends)
3. STL deque demonstration with basic operations
4. Circular queue with enqueue, dequeue, front, rear, isEmpty, and isFull
5. Function to reverse first K elements of a queue
6. Queue implementation using two stacks (efficient pop & peek)
7. Solution for counting students unable to eat lunch using queues
8. Reveal cards in increasing order using queue
ii) Stack Implementations
1. Array-based stack with operations (push, pop, reverse, display)
2. Linked list-based stack implementation
3. Remove consecutive duplicates from a string using stack
4. Next greater element and previous greater element problems
5. Stock span problem using …
=> Implement multiple queue and stack data structures with operations and problem solutions

c++/sorting/merge_sort.cpp, c++/sorting/quick_sort.cpp
Added a new sorting algorithm in C++ sorting section
=> Implemented merge and quick sort in C++

java/3Sum.java, java/Kadanes.java, java/MajorityNumber.java
1.  In three sum DSA code I have changed it from using ArrayList with pointers to HashSet, because sometimes using HashSet can make execution time faster.
2. Finding majority element or number from the given array to solve this question if we use map TC and SC would be O(n), but using Morris algorithm reduces SC to O(1).
3. Kadane's Algorithm is one of the most asked question in placements, so this is included.
=> Added optimized code and kadane's algorithm

c++/Graphs/find centre graph.cpp, c++/Linked Lists/reverse linkedlist.cpp
1.  Added 2 Cpp Code 
One in Graph  -:  Find Centre Graph 
Second in LinkedList -: Reverse Linked list
=> Added cpp dsa code

python/RemoveDuplicate.py
Added Remove Duplicates from sorted array in python
=> Added Remove Duplicates from sorted array in python

java/Levenshtein_distance/ReadMe.md, java/Levenshtein_distance/edit_distance.java
Added Levenshtein_distance  under the java/ folder.
Implemented Levenshtein distance (minimum edit distance) using Dynamic Programming.
Included:
- Standard DP solution (minDistance) with O(n × m) time and space.
- Added fun conversational comments (Buri Buri × Shino-suke style) to make the explanation engaging.
Given two strings word1 and word2, return the minimum number of operations required to convert word1 into word2.
Operations allowed: Insert, Delete, Replace a character.
Thank you @ghostmkg sir🌻 !!
=> Added Edit Distance  AKA ( Levenshtein Distance ) implementation in Java with comments and complexity analysis.

java/Palindrome.java
Introduces Palindrome.java with a method to check if a string is a palindrome and a main method for user input. Note: The isPalindrome method currently returns true if any matching pair is found, which may not be the intended logic.
=> Add Palindrome checker in Java

java/Anagrams.java
Implements a Java program that checks if two input strings are anagrams by comparing their sorted character arrays. Includes user input handling and case normalization.
=> Add Anagrams checker program in Java

java/BuyAndSellStock2Onwards/BestTimeToBuyAndSellStockWithCooldown.java, java/BuyAndSellStock2Onwards/BestTimeToBuyAndSellStockWithTransactionFee.java, java/BuyAndSellStock2Onwards/BuyAndSellStock2.java, java/BuyAndSellStock2Onwards/BuyAndSellStock3.java, java/BuyAndSellStock2Onwards/BuyAndSellStock4.java, java/BuyAndSellStock2Onwards/QuestionLinks
I have added the solutions of all the variations of buy and sell stock from leetcode along with the questions links of each question. To be specific following are the added questions solution :-
Buy and sell stock - 1
Buy and sell stock - 2
Buy and sell stock - 3
Buy and sell stock - 4
Buy and sell stock - with cool down
Buy and sell stock - with fee
Kindly let me know if anything is required for this PR to be merged.
Thanks & Regards
Firdaus Jawed
=> Buy and sell stock variations (from 2 onwards)

C/Two sum questions
PR Description:
This PR adds a C implementation for the Two Sum problem. Features:
Brute Force Approach: Checks all pairs to find the target sum. Optimized Hash-Based Approach: Uses a hash table to find the pair in O(n) time.
Handles arrays of integers and prints the indices of the elements whose sum equals the target. Includes example usage in main() for easy testing. Provides clear and easy-to-understand code for beginners. Demonstrates both simple and 
optimized approaches in C.
Type of Change:
[x] New Feature / Algorithm Implementation
=>  Add c solution for Two sum problem

java/RainWaterTrapping.java
Problem: Calculate total water trapped after raining given elevation heights.
Solution: Two-pointer approach with O(n) time, O(1) space complexity.
Features:
✅ Optimal two-pointer algorithm
✅ Handles edge cases (empty array)
✅ Multiple test cases with expected outputs
✅ Clean, efficient implementation
=> RainWaterTrapping

c++/Binary Trees/diameter_of_tree.cpp, c++/Binary Trees/lowest_common_ancestor.cpp
feat: add new Binary Tree algorithms - LCA, Diameter, Zigzag Traversal (closes #559)
- Added lowest_common_ancestor.cpp with recursive LCA implementation
- Added diameter_of_tree.cpp using height-based approach
- Added zigzag_traversal.cpp with BFS level toggle
- Includes example trees in each main() for testing
closes #559
=> feat: add LCA, Diameter, and Zigzag Traversal algorithms for BT

java/MaximumSubarraySum.java
Add Maximum Subarray Sum - Kadane's Algorithm
Problem: Find the contiguous subarray with the largest sum in an integer array.
Solution: Implemented Kadane's Algorithm with O(n) time complexity and O(1) space complexity.
Features:
✅ Basic maxSubarraySum() - returns maximum sum
✅ Enhanced maxSubarrayWithIndices() - returns sum with start/end indices
✅ Comprehensive test cases with expected outputs
✅ Clean, well-documented code
Test Cases:
[2, 3, -8, 7, -1, 2, 3] → 11 (subarray: [7, -1, 2, 3])
[-2, -4] → -2 (subarray: [-2])
[5, 4, 1, 7, 8] → 25 (entire array)
=> Maximum Subarray Sum

Arranging Coins Implementation.cpp
**Intuition**
100% beats solution
**Approach**
Only Math
**Complexity**
Time complexity:
O(1)
Space complexity:
O(1)
=> Arranging Coins Implementation.cpp

c++/Capacity To Ship Packages Within D Days Implementation.cpp
**Intuition**
We want to find the minimum ship capacity such that all packages can be shipped within days.
If the ship’s capacity is too small, we’ll need more days.
If the ship’s capacity is big enough, we may finish in equal or fewer days.
**Approach**
Range of Capacity:
Minimum capacity (low) = the heaviest single package, because at least that much space is needed.
→ *max_element(weights.begin(), weights.end())
Maximum capacity (high) = sum of all weights (carry everything in one trip).
→ accumulate(weights.begin(), weights.end(), 0)
Binary Search:
Take mid = (low + high)/2 as trial capacity.
Call findDays(weights, mid) to see how many days are needed.
If noOFdays <= days → we can try smaller capacity (search left).
Else → capacity too small → search right.
Final Answer = low (the …
=> Capacity To Ship Packages Within D Days Implementation.cpp

Count Negative Numbers in a Sorted Matrix Implementation.cpp
**🔹 Intuition**
We just need to count how many numbers are < 0.
Since the matrix is sorted row-wise and column-wise (non-increasing order), negatives are grouped toward the right-bottom.
Your solution simply brute-forces through every cell.
**🔹 Approach** 
Traverse all rows and columns.
For each element, check if < 0.
Maintain a counter.
Return the counter at the end.
**🔹 Complexity**
Time: O(m × n) (m = rows, n = columns).
Space: O(1).
=> Count Negative Numbers in a Sorted Matrix Implementation.cpp

c++/Find K Closest Elements Implementation.cpp
**Approach**
Find the index of the element closest to x.
Build a list of (distance, index) pairs for all elements.
Sort by distance (and index implicitly via sorting).
Take first k elements, map back to original values.
Sort result before returning.
**Complexity**
Time: O(n log n) → because of sorting.
Space: O(n) → storing distance-index pairs.
**Intuition**
We need k elements closest to x.
First, find the element closest to x.
Then, expand left and right to collect all candidates with their distance from x.
Pick the k smallest by distance, and finally sort them (since the answer must be in ascending order).
=> Find K Closest Elements Implementation.cpp

java/HappyNumber.java
Added solution for "Happy Number" in Java using HashSet.
Tracks previously seen numbers to detect cycles and determine happiness.
=> Added Happy Number solution in Java using HashSet

python/circular_subarray_palindrome_check.py
###Contributed 3 DSA programs in python. 
1) <ins>python/circular_subarray_palindrome_check.py</ins>
2) <ins>python/longest_balanced_substring.py</ins>
3) <ins>python/minimum_steps_to_equalize_towers.py</ins>
PR made by Dhairya Bhatt
=> Added 3 unique DSA problems with solutions in Python.

java/SortArrayListint.java
Added Java Program to Sort ArrayList of Integers in Ascending Order in java
1.SortArrayListint.java
=> Added Sort Array List in Integer

C/Binary_Search_Tree.c, C/Bubble_Sort.c, C/Merge_Sort.c, C/Queue.c, C/Quick_Sort.c, C/Singly_Linked_List.c, C/Stack.c
I added 5 files and updated 2 files, a total 7 files.
Added:-
1. Binary_Search_Tree.c
2. Merge_Sort.c
3. Quick_Sort.c
4. Singly_Linked_List.c
5. Stack.c
updated:-
6. Bubble_Sort.c
7. Queue.c
=> Added Binary Search Tree , Stack , Queue, LinkedList , Merge Sort, Quick Sort, Bubble Sort in C

javascript/bfs.js, javascript/dfs.js
- Implemented Depth-First Search (DFS) algorithm in JavaScript inside the `JavaScript/` folder.
- File: `dfs.js`
- Includes an example graph and traversal to demonstrate DFS order.
- Helps beginners understand DFS traversal in graphs and can be used as a reference for DSA practice.
Checklist:
-  Code runs without errors.
- Follows repository folder structure.
- Includes comments and example for clarity.
=> Add Depth-First Search (DFS) solution in JavaScript

python/container_with_water.py
added the python file container_with_water.py
=> added a python code

java/WordPattern.java
=> WordPattern in Java

c++/Add Arranging Coins Implementation in C++ #449.cpp, html/Avengers_website_basic.html, html/Forms_All_input_types.html, python/A_Skibidus_and_Amog_u.py, python/D_Fixed_Password.py, python/Sum_of_Even_Fibonacci_numbers.py
added c++/Add Arranging Coins Implementation in C++ #449.cpp issued by @janavipandole 
added basic HTML websites, one containing all the forms inputs.
added CodeForces questions (python).
=> Solved and Added different issues raised.

c++/Longest Palindromic Substring.cpp
I have the c++ solution to the leetcode problem "Longest Palindromic Substring".
The problem statement for the same is as follows:
Given a string s, return the longest palindromic substring in s.
Example 1:
Input: s = "babad"
Output: "bab"
Explanation: "aba" is also a valid answer.
Example 2:
Input: s = "cbbd"
Output: "bb"
Constraints:
1 <= s.length <= 1000
s consist of only digits and English letters.
=> Added new c++ code

go/Bellman_ford_algorithm.go
📌 Pull Request Description
What does this PR do?
Implements Bellman-Ford Algorithm in Go.
Solves the Single Source Shortest Path problem for weighted graphs, including those with negative edge weights.
Detects negative weight cycles in the graph.
Includes a main function with an example graph and test case for demonstration.
✅ Language
Go
🔗 Hacktoberfest
This PR is part of Hacktoberfest contribution . 
📝 Notes
The code is clean, well-commented, and follows best practices.
Easy to understand and ready for educational use or Hacktoberfest contributions.
=> Added Bellman Ford Algorithm in Go

c++/Binary Trees/zigzag_traversal.cpp
Implemented zigzag (spiral) level order traversal of a binary tree using BFS. The traversal alternates direction at each level, printing nodes left-to-right and then right-to-left on the next level.
=> zigzag traversal of binary tree

go/BFS_algorithm.go, go/DFS_algorithm.go
added the code for BFS and created a example , So a student can quickly understand what’s happening.
=> added BFS algorithm in go

java/407-traping-rain-water-ii/README.md, java/407-traping-rain-water-ii/traping-rain-water-ii.java, java/42-trapping-rain-water/README.md, java/42-trapping-rain-water/trapping-rain-water.java
- I created a folder inside Java as "407-traping-rain-water-ii"
- There I created two files:
> - traping-rain-water-ii.java: File where the solution is present
> - README.md: File where description about the problem statement is mentioned
=> Solution to Rain water harvesting II a intersting letcode problem

java/Largest_Rectangle_in_Histogram.java, java/Sliding_Window_Maximum.java, java/Trapping_Rain_Water_II.java
Add implementations for Largest Rectangle in Histogram, Sliding Window Maximum, and Trapping Rain Water II
=> Added java code

c++/Aggressive Cows.cpp
**🔹 Intuition**
If we try to place cows greedily with a fixed distance d, we can check whether it’s possible.
The answer space (the minimum distance between cows) is monotonic:
If we can place cows with distance d, then we can also place them with smaller distances.
If we cannot place cows with distance d, then we cannot place them with larger distances.
**🔹 Approach**
Sort stalls (since order of positions matters for distance).
Binary Search Range:
low = 1 (minimum possible distance).
high = max(stalls) - min(stalls) (largest possible distance).
Check feasibility (canPlace function):
Place the first cow in the first stall.
For each subsequent stall, place a cow only if the distance from the last placed cow is at least mid.
If we placed all k cows successfully, return true.
Binary Search …
=> Aggressive Cows.cpp

Allocate Minimum Number of Pages Implementation.cpp
**🔹 Intuition**
This is a Binary Search on Answer problem.
If we fix a maximum limit of pages (mid), can we divide books among m students without exceeding that limit?
If yes → maybe we can do better (reduce limit).
If no → the limit is too small, increase it.
This works because the answer lies between:
Lower bound: the maximum single book (since no student can get less than that).
Upper bound: the sum of all pages (if one student takes all books).
**🔹 Approach**
Base Check:
If m > n, return -1 (impossible).
Binary Search:
Set low = max(arr) and high = sum(arr).
While low <= high:
Pick mid = (low + high)/2.
Check if allocation is possible with max pages = mid.
Feasibility Check (isPossible):
Iterate through books, assign them to students greedily.
If adding a book exceeds mid, allocate to …
=> Allocate Minimum Number of Pages Implementation.cpp

go/dijkstra_algorithm.go
What does this PR do?
Adds Dijkstra’s Algorithm implementation.
Solves the Single Source Shortest Path problem in a weighted graph (with non-negative weights).
Implemented using a Priority Queue (Min-Heap) for efficiency.
Includes an example test case in main for demonstration.
✅ Language
Go 
🔗 Hacktoberfest
This PR is part of Hacktoberfest contribution.
=> implement Dijkstra's algorithm in Go

DSA#/Sorting-Algos/selectionSort.java
Added selection sort in Java under sorting methods
Added two examples of Selection sort
=> Add selection sort implementation in Java      ------  - 🍵🍵🍵 - ------

html/RandomColourGenerator.html, html/RandomQuoteGenerator.html
Added two new html projects in the html file:
1)  One project is random quote generator 
2)  Another is random color generator
=> Added two new html projects

rust/bfs.rs, rust/dfs.rs
Hi Maintainer,
I have added bfs and dfs algorithm code in rust
=> Added bfs algorithm and dfs algorithm in rust

java/MergeIntervals.java, java/NonOverlappingIntervals.java, java/ProductOfArrayExceptSelf.java
Added 3 java DSA problems -
1. Product of Array except self
2. Merge Intervals
3. Non overlapping intervals
=> Added java DSA problems

c++/array.cpp, c++/charTriangle.cpp
=> Concatenating two strings arr elements

c++/Container_With_Most_Water.cpp
I added today ( 4-10-2025 ) leetcode POTD correct solution, written in CPP.
=> Added leetcode Container With Most Water in C++

java/encapsulation.java
The program is to easily understand the encapsulation in java.
=> Encapsulation

c++/Linked Lists/LinkedList_basics/1.cpp, c++/Linked Lists/LinkedList_basics/10.insert_tail.cpp, c++/Linked Lists/LinkedList_basics/11.insert_position.cpp, c++/Linked Lists/LinkedList_basics/12.insert_element.cpp, c++/Linked Lists/LinkedList_basics/2.convert_arr_to_ll.cpp, c++/Linked Lists/LinkedList_basics/3.traversal_in_ll.cpp, c++/Linked Lists/LinkedList_basics/4.search_in_ll.cpp, c++/Linked Lists/LinkedList_basics/5.delete_head.cpp, c++/Linked Lists/LinkedList_basics/6.delete_tail.cpp, c++/Linked Lists/LinkedList_basics/7.delete_kth_element.cpp, c++/Linked Lists/LinkedList_basics/8.remove_element.cpp, c++/Linked Lists/LinkedList_basics/9.insert_head.cpp
This update adds implementations of basic linked list operations, including:
Convert array to linked list
Traversal in linked list
Search in linked list
Delete operations: head, tail, k-th element, specific element
Insert operations: at head, at tail, at specific position, insert element
These functions provide a foundation for practicing and building more advanced linked list problems.
=> Added linkedlist basic concepts

python/dice_roller.py, python/python password_generator.py, python/todo_list.py
add python code
1 python/dice_roller.py
2 python/python password_generator.py
3 python/todo_list.py
=> add python code

c++/Linked Lists/cycle_detection.cpp
This project implements Floyd’s Cycle Detection algorithm (Tortoise and Hare) to detect if a linked list contains a cycle.
- Detects whether a singly linked list has a cycle.
- Uses two pointers moving at different speeds to identify loops.
- Time Complexity: O(n)
- Space Complexity: O(1)
1. Compile the program:
```bash
g++ cycle_detection.cpp -o cycle_detection
./cycle_detection
=> Added solution for Cycle Detection in Linked List in C++

c++/Pacific Atlantic_Water_Flow.cpp, java/lowest_common_ancestor.java
=> Pacific atlantic water flow

html/HappyBday.html
Added a Happy Birthday Card Project in html folder, its main feature is the sound effect it produces, users can create different tunes as per there creativity. All over, a usefull project.
=> Added Happy birthday Card in Html

c++/Combination Sum.cpp
* Use **backtracking / DFS** to try building combinations.
* Keep track of a **remaining sum = target − (sum so far)**.
* At each recursion, iterate candidates from a given start index to avoid duplicates.
* You can pick the same candidate multiple times (so recursion reuses the same index).
* Stop (prune) when remaining < 0.
* When remaining == 0, record the current combination.
* Think of exploring a tree of decisions: “take this number” vs “move to next number.”
* Because you can reuse elements, you stay at the same candidate when you “take” it.
* Sorting and early stopping help you prune branches where the sum would exceed target.
* Backtracking lets you undo a choice and try other possibilities, ensuring you explore all valid combinations exactly once.
=> Combination Sum.cpp

java/BinarySearchTree.java, java/BinarySearchTreeTest.java
The file had several problems which was fixed
Duplicate and conflicting class definitions
Incomplete methods
Syntax errors
Mixed variable names (data vs key)
Unnecessary casting
=> Binary search tree error fix

c++/417-PacificAtlanticWaterFlow/417-PacificAtlanticWaterFlow.cpp, c++/417-PacificAtlanticWaterFlow/417-PacificAtlanticWaterFlow.java, c++/417-PacificAtlanticWaterFlow/README.md
This PR includes the implementation of the LeetCode problem 417: Pacific Atlantic Water Flow, marked as POTD for 5 Oct.
Added a dedicated folder `417-PacificAtlanticWaterFlow-POTD-5Oct` containing:
- README.md: Detailed problem statement, examples, constraints, approach, and complexity.
- 417-PacificAtlanticWaterFlow.cpp: C++ solution with main function to test example cases.
- 417-PacificAtlanticWaterFlow.java: Java solution with main function to test example cases.
Both solutions use iterative propagation to determine cells from which water can flow to both Pacific and Atlantic oceans.
Time Complexity: O(m * n)  
Space Complexity: O(m * n)
=> Add solution for 417. Pacific Atlantic Water Flow (POTD 5 Oct) in C++ and Java

php/WordSearch.php
Added solution for following problem
1) Word Search problem in PHP
=> Added solution for word search in php

c++/Graphs/topological_sort.cpp
code below uses a DFS-based topological sort within a Solution class, which is standard practice for competitive programming platforms. It correctly implements cycle detection using a state array (instead of just a boolean visited), which is essential for this problem.
=> code uses a DFS-based topological sort within a Solution class

c++/2104-sum-of-subarray-ranges.cpp
---
- Implements LeetCode Problem 2104 – Sum of Subarray Ranges in C++. 
- Efficiently calculates the sum of ranges (maximum - minimum) for all subarrays.
- Uses Monotonic Stack technique to find Previous/Next Greater and Smaller Elements.
- Achieves an optimized O(n) time complexity with clear and structured logic.
- Includes a main function with example input and expected output for easy verification.
---
- Each element’s contribution as both maximum and minimum is computed using index distances.
- Formula used:
- Sum = (Sum of contributions as Maximum) - (Sum of contributions as Minimum)
- This avoids brute-force enumeration of subarrays, ensuring high efficiency.
---
**C++**
---
This PR is part of the Hacktoberfest 2025 celebration 🎉
Aimed at contributing high-quality, optimized, and …
=> Added the leetcode problem 2104 sum of subarray ranges

c++/Articulation and Brifge points/Articulation_Point_Bridges.sublime-snippet
1) c++/Articulation and Brifge points/Articulation_Point_Bridges.sublime-snippet 
this is a very generic code snippet for articulation points and bridges concept used in competitive programming
=> [c++/Articulation and Brifge points/]--> Added articulation points and  bridges code snippet

java/Rotate_array.java, java/TopologicalSort.java, java/Tower_Of_Hanoi.java
tower_of_hanoi 
topological-sort
rotation_array
=> Adding the java questions

c++/Array/NextGreaterElement.cpp
Added C++ DSA code -
1) Next Greater Element
=> Added Next Greater Element C++ solution

rust/min_max_array.rs, rust/reverse_array.rs, rust/rotate_array.rs
added 3 Rust DSA codes
1] min_max_array.rs
2] rotate_array.rs
3] reverse_array.rs
=> added Rust DSA codes

python/Graphs_BFS_Tranversal.py
Optimised Graphs BFS Transversal
=> Graphs BFS Transversal

longest_palindromic_substring.py
Implemented longest palindromic substring in Python for Hacktoberfest
=> Added longest_palindromic_substring.py solution

python/Swiminrisingwater.py
This PR adds a Python implementation for a good Graph concept question (Title)- "Swim in Rising Water" for issue #667 .
Uses a Dijkstra-style min-heap approach with O(n² log n) complexity.
File added at python/Swiminrisingwater.py
Closes #667 .
=> Add Python solution for - Swim in Rising Water

java/778-swim-in-rising-water/README.md, java/778-swim-in-rising-water/swim-in-rising-water.java
- I created a folder inside Java as "407-traping-rain-water-ii"
- There I created two files:
>- traping-rain-water-ii.java: File where the solution is present
>- README.md: File where description about the problem statement is mentioned
=> Add todays daily problem solution Swim in rising water

javascript/addno.js, javascript/countdowntimer.js, javascript/evenoroddcheck.js, javascript/largenoinarray.js, javascript/reverse_string.js, python/Binarytreetraversal.py, python/Stack.py, python/bubblesort.py
Added Python DSA code
1.python/Binarytreetraversal.py
2.python/Stack.py
3.python/bubblesort.py
Added JS code
1.javascript/addno.js
2.javascript/countdowntimer.js
3. javascript/evenoroddcheck.js
4. javascript/largenoinarray.js
5. javascript/reverse_string.js
=> Added Python DSA code and Added JS code

c++/Array/Kadane.cpp
=> Kadane Algorithm 

c++/Graphs/kruskals_algorithm.cpp
- Implemented Kruskal’s Algorithm for MST using Disjoint Set Union
- Added detailed comments and problem explanation
- File path: CPP/graphs/kruskals_algorithm.cpp
- Follows repository contribution structure and naming rules
=> Added kruskals_algorithm.cpp (C++ solution using DSU and Greedy Approach)

python/Ancient_Library.py
Problem Statement : You've stumbled upon a collection of ancient scrolls in a long-forgotten library.Each scroll is represented by a string of symbols. You quickly realise that many scrolls are just different arrangements of the same set of symbols—meaning they are fragments of the same original manuscript.
=> I added a new problem of Ancient_Library in python

README.md, roadmap/DSA Road Map Basic to Advance.md
----------------------------------------------------------------------------------------------------------------------------
PR #503 
----------------------------------------------------------------------------------------------------------------------------
Currently, the repository has a solid structure and contribution guide, but it lacks a **step-by-step DSA roadmap** to guide learners and contributors on which problems or topics to focus on.  
This roadmap is designed to help both beginners and advanced learners practice systematically.  
---
- Added a **DSA Roadmap document** in the repository  
- Structured topics from **Beginner → Intermediate → Advanced**  
- Covered problem categories such as:
- Arrays
- Strings
- Recursion
- Linked Lists
- Stacks & Queues
- Trees
- Graphs
- …
=> DSA Roadmap for Learners and Contributors 

java/dynamic_programming/PaintHouse/paintHouse1.java, java/dynamic_programming/PaintHouse/paintHouse2.java
This PR contains dynamic programming solutions for the Paint House problem family, where the goal is to minimize the total cost of painting a row of houses such that no two adjacent houses have the same color. The branch includes implementations for both the classic three-color version and the generalized k-color version, with clear examples and algorithmic explanations.
=> Paint house series in java

java/HouseRobber/houseRobber1.java, java/HouseRobber/houseRobber2.java
Hi there,
I have added the problem statement of house robber 1 and house robber 2 along with the solution and the logic behind it. The solution is well commented.  If anything else is neede for the PR to be merged, kindly let me know
=> House robber 1 and house robber 2 in Java

c++/Array/QuickSort.cpp
This program implements the Quick Sort algorithm in C++, one of the most efficient sorting techniques based on the divide-and-conquer paradigm. The algorithm works by selecting a pivot element, partitioning the array around the pivot so that elements smaller than the pivot are placed to its left and larger ones to its right, and then recursively sorting the subarrays.
In this implementation, the last element of the array is chosen as the pivot. The partitioning is performed using in-place swaps, making the algorithm memory-efficient. The recursion continues until all subarrays are reduced to single elements, resulting in a completely sorted array.
=> Added Quick Sort Code in cpp

c++/fenwick_tree.cpp, python/trie_implementation.py
Added a comprehensive Fenwick Tree (Binary Indexed Tree) implementation in C++ with advanced features.
- **Basic FenwickTree class** with update, query, and range operations
- **RangeFenwickTree** for efficient range updates and queries
- **Utility functions** for inversion count and kth smallest element
- **Comprehensive documentation** and complexity analysis
- **Demo function** showing all operations and use cases
- **Perfect for competitive programming** and range query problems
- Time Complexity: O(log n) for update and query operations
- Space Complexity: O(n)
- Includes advanced features like range updates and lazy propagation
- Utility functions for common competitive programming problems
- Includes comprehensive demo function with multiple test cases
- All operations tested and …
=> Add comprehensive Fenwick Tree (Binary Indexed Tree) implementation in C++

python/find_leaders.py
Implement a function to find leaders in an array.
Solves #626
=> Added find_leaders.py under the python directory

python/Successfulpairofspellsandpotions.py
This PR #725 adds a Python implementation for DSA problem - "Successful Pairs of Spells and Potions".
Uses a Dijkstra-style min-heap approach with O(n log m) complexity.
File added at python/Successfulpairofspellsandpotions.py
Closes #725
=> Add python solution for - Successful Pair of Spells and Potions

c++/allSTL/Vector.cpp
- initialisation
- push_back
- front
- back
- iterator
- for each
- erase
- size
- access element
- swap
- clear
=> C++ STL (Vector)

java/SearchInStrings.java
Added a Java program to search for a target character in a string using two approaches:
Method 1: charAt() iteration
Method 2: toCharArray() iteration
Handles empty strings and prints whether the target character is found
Example usage included in main()
=> feat:Add search for a charcter in string using charAt() & toCharArray()

python/AvoidFloodInTheCity.py
Added 1 python DSA problem- Avoid flood in the city problem
=> added solution for avoid flood in the city problem in python

java/StreamDemo.java
This PR adds a Java program (StreamDemo.java) that demonstrates:
- Mapping values using streams
- Filtering list elements
- Collecting results into List and Set
- Sorting and printing elements
It also compares traditional loops with Stream-based one-liners for cleaner and more functional Java code.
=> Added StreamDemo.java for Java Stream API example

java/StreamDemo.java
This PR adds a Java program (StreamDemo.java) that demonstrates:
- Mapping values using streams
- Filtering list elements
- Collecting results into List and Set
- Sorting and printing elements
It also compares traditional loops with Stream-based one-liners for cleaner and more functional Java code.
=> Add StreamDemo.java demonstrating Stream API usage

SQL/EmployeeBonus.sql, SQL/ProjectEmployeesI.sql, SQL/SalesPerson.sql, SQL/SwapSalary.sql
Added SQL Queries 
1) Employee Bonus
2) Project Employees I
3) Sales Person
4) Swap Salary
=> Added SQL queries

python/DynamicProgramming/LongestPalindromicSubsequence.py
<html>
<body>
<h2 data-start="1802" data-end="1820">🔍 How It Works</h2>
<ol data-start="1822" data-end="2339">
<li data-start="1822" data-end="1936">
<p data-start="1825" data-end="1936"><strong data-start="1825" data-end="1838">DP Table:</strong> <code data-start="1839" data-end="1849">dp[i][j]</code> stores the length of the longest palindromic subsequence in the substring <code data-start="1924" data-end="1933">s[i..j]</code>.</p>
</li>
<li data-start="1937" data-end="2005">
<p data-start="1940" data-end="2005"><strong data-start="1940" data-end="1954">Base Case:</strong> Single characters are palindromes of length <code data-start="1999" data-end="2002">1</code>.</p>
</li>
<li data-start="2006" data-end="2172">
<p data-start="2009" data-end="2024"><strong data-start="2009" …
=> Implement longest palindromic subsequence function

html/Valentine_project.html
Instead of a simple plain background i have enhanced the background by giving linear gradient which looks better now.
=> Enhanced Background
